### ISSUE TITLE
IRI Fails on Windows with exit code "1"

### ISSUE THREAD

**Issue by romansemko** [SemkoDev/bolero.fun#1]
Seems to be related to: https://github.com/iotaledger/iri/issues/350
Manual start of IRI produced the same error described in the ticket.

It doesn't make sense implementing https://github.com/iotaledger/wallet/issues/773#issuecomment-352172896 solution. The best approach is to wait for a fix in IRI.

**Comment by ghost** [comment]
For me, downloading http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html Version  Java SE Development Kit 8u151 vor x64 saved that issue.

**Comment by SeeUnsharp** [comment]
Works for me too (Win 10 64bit)

**Comment by realFlowryan** [comment]
Installing  Java SE Development Kit solved it for me aswell. 
Win 10 Home x64

**Comment by ssssss789** [comment]
i install both 32bit java and 64bit

**Comment by f-ben** [comment]
if you run iri from commandline it most probably gives you an error message.
error 1 also applies to "dependencies missing" which from what I understand comes from rocksdb trying to load files from MS visual C++ runtimes. If you install MS C++ Runstimes 2017 the error is gone.

**Comment by F0rt1s** [comment]
Installing Java SE Development Kit x64 worked for me too.

**Comment by heikog** [comment]
had this on osx - java update fixed it

**Comment by romansemko** [comment]
Please make sure you have the correct Java installed. *Running 32bit Java on a 64bit machine might crash IRI*. If in doubt, install java from here, selecting correct bit version (32 or 64) depending
on your machine: https://www.java.com/en/download/manual.jsp
Restart your computer to take effect.
Also *IMPORTANT*, download and install the latest *Visual C++ redistributable* from here (due to a bug reported in IRI): https://download.visualstudio.microsoft.com/download/pr/11100230/15ccb3f02745c7b206ad10373cbca89b/VC_redist.x64.exe

**Comment by adertask** [comment]
Hi Roman,

I still have this error / problem.

What else can I do? Do you have any ideas?

System
Win10 64bit
Java SDK 64 (all others deinstalled) (java_home is set)
MS Redistributable 2017x64 (beneath 2015x86, 2013x86, 2013x64, 2012x86, 2012x64, 2008x86, 2008x64)
deleted content of AppData\Local\Temp folder
restarted

Greetings
Mario

log
=====
Fri Mar 16 2018 13:31:03 GMT+0100 (Mitteleuropäische Zeit) field: IRI down. Retrying in 30s...
Fri Mar 16 2018 13:30:34 GMT+0100 (Mitteleuropäische Zeit) iri: ERROR: IRI exited with status 1
Fri Mar 16 2018 13:30:34 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: 03/16 13:30:34.666 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 

java.lang.NullPointerException: null

	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.2.2.jar:na]

	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.2.2.jar:na]

	at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.2.2.jar:na]

	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:247) ~[iri-1.4.2.2.jar:na]

	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]


Fri Mar 16 2018 13:30:33 GMT+0100 (Mitteleuropäische Zeit) field: IRI down. Retrying in 30s...
Fri Mar 16 2018 13:30:28 GMT+0100 (Mitteleuropäische Zeit) iri: STDOUT: 03/16 13:30:28.634 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...


Fri Mar 16 2018 13:30:28 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: java.lang.UnsatisfiedLinkError: C:\Users\xxx\AppData\Local\Temp\librocksdbjni836531578315398322.dll: Eine DLL-Initialisierungsroutine ist fehlgeschlagen

	at java.lang.ClassLoader$NativeLibrary.load(Native Method)

	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)

	at java.lang.Runtime.load0(Runtime.java:809)

	at java.lang.System.load(System.java:1086)

	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)

	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)

	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)

	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)

	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)

	at com.iota.iri.Iota.initializeTangle(Iota.java:201)

	at com.iota.iri.Iota.init(Iota.java:92)

	at com.iota.iri.IRI.main(IRI.java:73)


Fri Mar 16 2018 13:30:28 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: Exception in thread "main" 
Fri Mar 16 2018 13:30:03 GMT+0100 (Mitteleuropäische Zeit) iri: STDOUT: 03/16 13:30:03.836 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.2.2


Fri Mar 16 2018 13:30:03 GMT+0100 (Mitteleuropäische Zeit) field: IRI down. Retrying in 30s...
Fri Mar 16 2018 13:30:02 GMT+0100 (Mitteleuropäische Zeit) iri: starting...
Fri Mar 16 2018 13:30:02 GMT+0100 (Mitteleuropäische Zeit) system: Java version detected: [1.8.0_161
]
Fri Mar 16 2018 13:30:02 GMT+0100 (Mitteleuropäische Zeit) system: Java version line: [java version "1.8.0_161"
]
Fri Mar 16 2018 13:30:02 GMT+0100 (Mitteleuropäische Zeit) system: Java: 
java version "1.8.0_161"

Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)


Fri Mar 16 2018 13:30:02 GMT+0100 (Mitteleuropäische Zeit) field: Public ID: 40023fd04cfd9b54
Fri Mar 16 2018 13:30:02 GMT+0100 (Mitteleuropäische Zeit) field: Field ID: 40023fd04cfd9b548284ee0c1b98798f2dec0e5c60f912981486fd121a7a319f
Fri Mar 16 2018 13:30:02 GMT+0100 (Mitteleuropäische Zeit) field: Field Client v.0.1.5
