### ISSUE TITLE
IRI fails to start error 4294967295

### ISSUE THREAD

**Issue by f-ben** [SemkoDev/bolero.fun#10]
IRI crashes with error 4294967295 on Windows 10 x64 1709 with Java 1.8.0 151. Error indicates that another Java process is running but that´s not the case. Only thing I noticed is that bolero spawns two new processes when starting which may be the cause of this issue. See attached screenshot.

![notherjavaproc](https://user-images.githubusercontent.com/2088471/34649809-71e0d670-f3b6-11e7-8305-7ea590c7dbc0.png)

**Comment by Marsinator** [comment]
same issue, additional wisdom:

https://i.imgur.com/ZtyptQs.png

**Comment by romansemko** [comment]
Seems related: https://github.com/iotaledger/wallet/issues/158
It seems that there is another java process running in the background. Try killing all java in the process manager and start bolero again. This is the solution provided in the ticket above. Let's hope it solves ours as well.

**Comment by f-ben** [comment]
I know that the errorcode says that there is another java running in the background - thats why I attached the screenshot of the taskmanager. There is definitely not running any java application/update/setup or what so ever running in the background.

The only thing I noticed is that when I start bolero it creates two new bolero processes but I am not sure if this is intended. I also did a fresh windows install as a virtual machine, did all windows updates, installed java 8 151, installed VS C++ runtimes and bolero. I did not install any other software or ran any other setup but still kept getting this error message.
  
Edit: Btw if bolero gives me this error message I indeed can start IRI using the commandline and IRI itself works

**Comment by romansemko** [comment]
Maybe the double-bolero processes is the problem. It should be one as far as I can tell from Mac/Linux perspective. Not sure how electron handles the processes on windows.

Can you try starting bolero.fun.exe from command line?

**Comment by f-ben** [comment]
I did but sadly it didn't help - same error. I also tried without windows defender because I thought that the file might be locked but no success.

**Comment by romansemko** [comment]
Got another user confirming that running IRI through bolero generates error, while running directly doesnt

**Comment by romansemko** [comment]
Should be fixed with v0.1.10
