### ISSUE TITLE
Unable to resize Bolero GUI

### ISSUE THREAD

**Issue by boxcee** [SemkoDev/bolero.fun#12]
I am unable to resize the Bolero GUI, therefore I cannot view the full node URL

[Screenshot](https://imgur.com/a/ru4cn)

**Comment by witwit** [comment]
It is not meant to be resizable for now. However, I will increase the height of the window so that the last row is visible on all platforms.

**Comment by witwit** [comment]
Will be fixed in the next release:
![bolero-gui-resized](https://user-images.githubusercontent.com/1893589/34667170-1cf76b62-f468-11e7-8787-982428280f5f.png)
