### ISSUE TITLE
JavaScript uncaught exception

### ISSUE THREAD

**Issue by OleWouters** [SemkoDev/bolero.fun#13]
Getting this error when I run Bolero.
Using Java SDK 151

![afbeelding](https://user-images.githubusercontent.com/6282561/34654085-98472e1e-f3f6-11e7-854e-3a1ce486786e.png)

**Comment by witwit** [comment]
@romansemko , I think it happens in bolero.lib system.js:60-61

**Comment by OleWouters** [comment]
I used the 152 SDK after. Also placed bolero in my home folder and it seems to be running properly. Gonna download the new release now
