### ISSUE TITLE
folders  - Usersstefan.bolerodb / bolerodbixi

### ISSUE THREAD

**Issue by ssssss789** [SemkoDev/bolero.fun#14]
i have also 10 gb in users/..../.bolero

and here 1,2 gb

![bolero](https://user-images.githubusercontent.com/23654955/34664478-66256278-f45c-11e7-9091-7e4942d3c1e3.PNG)

**Comment by UmbahaSpodPaha** [comment]
The same for me - Win7x64 JDK9

**Comment by romansemko** [comment]
This is most probably the reason why the windows Bolero is not being synchronised. Thanks for the screenshots and reporting. Very valuable!

**Comment by romansemko** [comment]
The reason is probably that the paths that nodeJS generates and writes for IRI are misinterpreted by Java/IRI (forward/backward slash issue) and the path to db folder is not where the database is being downloaded into.

**Comment by UmbahaSpodPaha** [comment]
When it will be fixed, we will need to redownload whole database and stuff? Mine iri sync is stuck always 50-100 ahead of current milestone.

**Comment by romansemko** [comment]
It shouldn't be needed. Please download v0.1.10. Remove the Usersstefan.* folders. They are not needed. Start the new Bolero. It should find and use the formely downloaded database.
