### ISSUE TITLE
Database error: Connection timeout

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [SemkoDev/bolero.fun#20]
Fresh install, can't even start to download database. In my home directory i have only "iri-1.4.1.6-bolero.jar" downloaded under "iri" category

error: connect ETIMEDOUT
148.251.71.85:80

![y5fye37](https://user-images.githubusercontent.com/35224101/34677881-c7f78a46-f491-11e7-8dc1-65bb45d833f6.png)

Windows 7 x64 JDK9

**Comment by romansemko** [comment]
Could you please try within an hour. The service might be unreachable.

**Comment by UmbahaSpodPaha** [comment]
Service is online again. Downloading! :)
