### ISSUE TITLE
IRI never syncs

### ISSUE THREAD

**Issue by sloganking** [SemkoDev/bolero.fun#23]
win10 v0.1.9
- "IRI Synchronized?" sits at "No (243000/3#####)" forever.
*pound sign is because I forgot the exact number but I assumed it was the current milestone height.*
- after a couple hours it it went up to "2435##" and sat there for 12 more hours.
- Edit1: using localhost and connecting from the GUI light wallet, could connect to wallet and see transaction history but all transactions showed as pending and thus balance displayed as zero.

win10 v0.1.10: 
- "IRI Synchronized?" sits at "No (243000/243000)" forever.
- Edit1: using localhost and connecting from the GUI light wallet, connection is refused.

Example from v0.1.10: https://i.imgur.com/Vj777dk.png

**Comment by ssssss789** [comment]
![iotairi](https://user-images.githubusercontent.com/23654955/34686207-25239476-f4ab-11e7-8313-4af47fd82ca0.PNG)

**Comment by ssssss789** [comment]
now my bolero stuck after 100%, at unzipping, if i found archive 9gb in temp, i try to unzip it says corupted archive,  so i downloading manually DB and will unzip with winrar to .bolero/db

http://db.iota.partners/IOTA.partners-mainnetdb.tar.gz

after 30 minutes i will see
/nothing, stuck at 243000

**Comment by footloosejava** [comment]
Same here. After the initial sync, it indicated synced. Now, on restart, says not synced although CPU use is quite high and it is def communicating.

**Comment by witwit** [comment]
As far as I know, if you re-start the state goes back to the original milestone. Therefore, restarting the app means you will start again with an un-synced app. FYI @romansemko

**Comment by footloosejava** [comment]
>As far as I know, if you re-start the state goes back to the original milestone.
You mean that simply starting and stopping does this?
So delete home/bolero and then start fresh, right?

**Comment by romansemko** [comment]
It jumps always ack to 243000 after the restart, but the sync takes much less time. That's how IRI works at the moment.

**Comment by footloosejava** [comment]
I did a fresh restart (clean start) and it finished download, then still stays at 243000. CPU is very busy, lots of network too but still at 243000.

Solution?

... and it is now synced. That was weird! Maybe there needs to be some sort or messaging to indicate the sync status a bit more finely so that the stuck block number does not look like a completely stuck sync.

**Comment by romansemko** [comment]
It's numbers directly taken from IRI. Not sure how to fine-grain show them without having them provided by the IRI!
