### ISSUE TITLE
More that 4GB RAM required?

### ISSUE THREAD

**Issue by sanktk** [SemkoDev/bolero.fun#24]
Bolero refuses to run on my laptop with Win7x64 and 4GB of RAM. Free RAM is 3.87 GB as seen in task manager. Is 3.87 GB really not enough or need the checks a bit of tweaking?

**Comment by joshirio** [comment]
Most 4GB systems have in fact only 3.8x GB for some reason. Would be great if the check could tolerate 3.6+ GB systems, unless it is really required (bolero uses 2.2 GB on my system so far).

**Comment by romansemko** [comment]
okay, will adapt. Guess we will have to wait and see. The synchronisation might fail on less RAM.
