### ISSUE TITLE
[tmpfs] Not enough space error on Linux

### ISSUE THREAD

**Issue by joshirio** [SemkoDev/bolero.fun#25]
Bolero complaints about space on Linux:
![bolero](https://user-images.githubusercontent.com/12795018/34711820-f937a3f4-f520-11e7-842d-14db6eff3279.png)

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
dev             5.9G     0  5.9G   0% /dev
run             5.9G  1.4M  5.9G   1% /run
/dev/dm-0       915G  223G  647G  26% /
tmpfs           5.9G   50M  5.9G   1% /dev/shm
tmpfs           5.9G     0  5.9G   0% /sys/fs/cgroup
tmpfs           5.9G   36M  5.9G   1% /tmp
/dev/sdc1       976M   94M  815M  11% /boot
tmpfs           1.2G   44K  1.2G   1% /run/user/1000
```

Home directory has plenty of space.
Looks like Bolero is checking the temporary directory (handled by tmpfs) on linux for at least 8 GB.
Since, as far as I know, the database is downloaded to the .bolero folder in the home directory, is this really required to have such a huge tmpfs?

OS: Arch Linux / Manjaro
Kernel: 4.14.12
RAM: 12GB

**Comment by witwit** [comment]
@romansemko , I think the issue was taken care of already?

**Comment by romansemko** [comment]
The database already is over 5GB big. And with each passing day it gets a little bigger. Considering this, we need to make sure there is plenty of space for few months ahead.

I will add configuration option to change the location of database download or download to the same .bolero folder. Adding to features list for discussion...
