### ISSUE TITLE
Download stops on OSX screensaver

### ISSUE THREAD

**Issue by armstrys** [SemkoDev/bolero.fun#29]
During install download keeps stopping if screensaver and lockscreen take over. This issue happens even when disks stay active. Install was only successful by disabling sleep and screensaver functionality.

**Comment by romansemko** [comment]
It might be that only the windows freezes after screensaver. Have you tried closing and re-opening the window again.

The sleep might break the download process. This is confirmed.

**Comment by armstrys** [comment]
I have not tried that. I can give it a shot later today and see if I can reproduce! Thanks.

**Comment by armstrys** [comment]
Sorry a little delayed... Just tried to uninstall and reinstall to test it out. I deleted the app and the Bolero files in the OSX library folder. When I reinstalled it seemed to just fire right back up! Any tips for doing a full uninstall so that I can try again? On that note, adding an uninstall package would probably be a good idea if there are some other hidden files lurking on the computer.

**Comment by romansemko** [comment]
Please try the following:

1. Remove the bolero folder (where bolero exe is located) and .bolero folder from your home directory.
2. Download the newest Bolero version 0.1.13
3. Start and see if it works.

Please re-open the ticket if you see the problem persist.
