### ISSUE TITLE
Database error: Invalid tar header.

### ISSUE THREAD

**Issue by r-c-k** [SemkoDev/bolero.fun#30]
When finished downloading the database, Bolero is giving me the bummer message with an database-issue named: "error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"

Im on Ubuntu 17.10.

**Comment by ssssss789** [comment]
you can try manually download and unzip to /db http://db.iota.partners/IOTA.partners-mainnetdb.tar.gz

but for me never bolero works, cant get sync, still "almost", cca 10 milestones under full syncing, win10 64bit

**Comment by romansemko** [comment]
Seems that the database snapshot was corrupted for some reason. Maybe an issue at iota.partners. Please try re-downloading.
