### ISSUE TITLE
Java version issue on High Sierra

### ISSUE THREAD

**Issue by pascalbros** [SemkoDev/bolero.fun#31]
Hi, just installed from the "release" section and got this screen:
![schermata 2018-01-10 alle 14 00 18](https://user-images.githubusercontent.com/293779/34774218-c42c24ca-f60e-11e7-8e05-fddeee1bae51.png)

My Java version:

![schermata 2018-01-10 alle 14 00 23](https://user-images.githubusercontent.com/293779/34774231-cf07e514-f60e-11e7-94d0-ff5438610ea6.png)

What can I check?

Thanks

**Comment by romansemko** [comment]
Please try version 0.1.13. It will report java version feedback in the logs view in Bolero. If it still gives you problems, could you past the logs from the logs view? Thanks!

Use the ticket #41 for feedback. I will close this as duplicate.
