### ISSUE TITLE
Windows client never fully syncs

### ISSUE THREAD

**Issue by ghost** [SemkoDev/bolero.fun#34]
It seems that the Windows client never fully syncs.

After like 12 hours after initial startup I have a .bolero db folder of approximately 11.6GB.
The IRI synchronized status only updates if you restart Windows. So let's say I'm stuck at 324432/324780. I restart, and then it shows: 324784/324789. The latest milestone number (second part) does update while running the app. But the first number only updates if you restart the system. So it seems like it never fully syncs, but maybe it does in the background?

![untitled](https://user-images.githubusercontent.com/35333560/34824419-9e79d4dc-f6ce-11e7-9263-4bf5565c1541.png)

**Comment by ghost** [comment]
Some more info: I tried to connect a light wallet to it. But when trying to login it fails on the POST-request "getInclusionStates" with {
    "error": "The subtangle is not solid",
    "duration": 109310
}.

**Comment by ghost** [comment]
Same here, it seems like the current milestones are growing quicker than we can think, so I'm also anytime behind 10-20, example

T (Now) = (324970/325011)
T-1 hour = (324970/324990)
T-2 hour = (324935/324951)

**Comment by H3n-42** [comment]
The syncing process sometimes takes up to days. Sometimes the UI freezes, but the syncining process is running in the background.

**Comment by cometax** [comment]
I let mine run for 3 days now. The local is almost always stuck in a specific number, although the actual iri number updates. After rebooting and reloading, the number updates to something much closer to iri and then stops until next restart. It never fully synchronizes. I'm 45 behind (328130/328175).

**Comment by romansemko** [comment]
Please try the latest version 0.1.13 and let me know how it goes! It comes with the custom IRI 1.4.1.7 that should sync faster.

Please reopen if you see bolero still taking +5 hours or days to sync on windows.

**Comment by ghost** [comment]
@romansemko I'm testing now. It still needs a lot more time to sync than 5 hours. At the moment the IRI synchronized status still shows (243000/335842) and it's been syncing for 18 hours.

The size of the db-folder is currently around 9.1GB.

**Comment by romansemko** [comment]
Please upgrade to 0.1.14 after the snapshot the database is tiny and fill sync much, much faster.
