### ISSUE TITLE
Show latest IRI messages (Bell button) by default. 

### ISSUE THREAD

**Issue by huggre** [SemkoDev/bolero.fun#35]
When opening the IRI message window (Bell button) the scroll bar automatically goes to top and i have to manually drag it to bottom to see the latest IRI messages.
The scrollbar should move to the bottom and show the latest IRI messages by default.
If you want to show previous messages you can scroll upwards.

**Comment by romansemko** [comment]
This has been added to v0.1.13. Please download.
