### ISSUE TITLE
Describing Log Protocoll

### ISSUE THREAD

**Issue by ghost** [SemkoDev/bolero.fun#36]
Is it possible to input any short help into the Log in the client, which is explaining what this information means? So what means "toBroadcarst", ....

Thu Jan 11 2018 19:04:35 GMT+0100 (Mitteleuropäische Zeit) iri: STDOUT: 01/11 19:04:35.523 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3 , toReply = 0 / totalTransactions = 3283258

![image](https://user-images.githubusercontent.com/35180255/34840133-53aab1f2-f704-11e7-97b7-663f18bada28.png)

**Comment by H3n-42** [comment]
This is the output of iri, the node itself. When you want to have the output changed, you should insert the issue here: https://github.com/iotaledger/iri

adding aditional informations, like a small "what is this and that" could be done withing bolero.

**Comment by romansemko** [comment]
I have added this to a nice-to-have list for further discussion.
