### ISSUE TITLE
IOTA wallet doesn't sync at login

### ISSUE THREAD

**Issue by milanezule** [SemkoDev/bolero.fun#38]
And I cannot get to my wallet. Any idea why this is happening and how to fix it? Thanks for suggestions!
![iota wallet not synced](https://user-images.githubusercontent.com/35399805/34906585-01acdfa0-f836-11e7-8ed3-69a0542e3f94.png)

**Comment by milanezule** [comment]
I did some more "digging" and I realized that my milestoneindex and solidsubtanglemilestoneindex are not the same and I understand they need to be. Plus they need to be the same as the latest number in the #botbox on Slack. But where do I find the latest #botbox numer on Slack? Where do I access it? Thank you guys for any/all advice!

**Comment by H3n-42** [comment]
yes they need to be in sync, the process normaly takes some time (maybe days).
you can go into discord: https://discord.gg/fNGZXvh to see the current #botbox channel. (This number might be off by 1 or 2)

Currently not having an invite link for slack here, sry
