### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by OleWouters** [SemkoDev/bolero.fun#39]
![afbeelding](https://user-images.githubusercontent.com/6282561/34909487-64a784cc-f8a2-11e7-90bb-ee2cffd79e36.png)

Running 152 SDK

**Comment by romansemko** [comment]
Hi, do you still remember at what time the error happened? Was it just after starting the app or after a while?
Windows cuts off the stack trace at the end so I do not see where exactly the error happened. That's very unfortunate. :(

**Comment by OleWouters** [comment]
It happened right after I started the app. The bolero screen showed, there was a yellow triangle for both IRI and Nelson, so they were starting, and then the error appeared. Sometimes, not sure if related to this error. Bolero/Java crashes and completely remove the bolero exe from my computer meaning I have to unzip everything again.

**Comment by romansemko** [comment]
maybe an antivirus? I had reports in the past that bolero was detected as a virus by some antiviruses. The error might be related as well.

**Comment by romansemko** [comment]
@OleWouters can you please try v 0.1.14 and see if it works?

**Comment by OleWouters** [comment]
Had some problems with Bitdefender but everything is running smoothly now!

**Comment by romansemko** [comment]
Thanks for your input! Closing this...
