### ISSUE TITLE
error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by toddmera** [SemkoDev/bolero.fun#42]
Any ideas why I get this error?
./bolero.fun: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by toddmera** [comment]
Wait...does this have to have the linux GUI?  Is there an option for using from just the CLI?

**Comment by romansemko** [comment]
Yes. You can use just Nelson + IRI. Bolero is supposed to be run in desktop / GUI environments.
