### ISSUE TITLE
IRI Synchronized? No 

### ISSUE THREAD

**Issue by xq0404** [SemkoDev/bolero.fun#47]
After installing the Bolero, there is no "downloading.." status, it shows "IRI Synchronized? No" both on Win 10 and Win7. I can't manually download and sync, either.

**Comment by romansemko** [comment]
On windows, the snapshot downloading is disabled at this moment, unfortunately. It has to manually synchronise, which is currently quite painful on all Windows versions. We are trying to find a solution to make IRI/RocksDB work on Windows.

**Comment by xq0404** [comment]
Thanks for the reply. No wonder.
