### ISSUE TITLE
Database download error

### ISSUE THREAD

**Issue by abel30567** [SemkoDev/bolero.fun#49]
As soon as it finished downloading the database I get the following error:

"error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"

Any clue how to fix this?

**Comment by Andersmholmgren** [comment]
yeah I got that too after waiting hours for the download :-(

I would attach the log file but can't find it.

Bolero: Alpha 0.1.13
Mac OS: 10.13.3 (17D47)
Java: Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**Comment by kongjames-zz** [comment]
As soon as I opened bolero.fun, it couldn't install iri and db. java is 9.0.4.

Bolero: Alpha 0.1.14
MacOS: 10.13.2
 
![screen shot 2018-01-29 at 2 13 12 am](https://user-images.githubusercontent.com/14840912/35497878-073a289a-049a-11e8-9458-42ce79c8394b.png)

**Comment by romansemko** [comment]
Please try 0.1.14. The database is much smaller after the snapshot. This might solve this issue for now, at least.

**Comment by kongjames-zz** [comment]
I get that error as soon as I boot up 0.1.14...

**Comment by Andersmholmgren** [comment]
0.1.14 worked for me. Thanks
