### ISSUE TITLE
can't scroll down in Balero UI

### ISSUE THREAD

**Issue by dennysemko** [SemkoDev/bolero.fun#5]
it's stuck at this position
![capture](https://user-images.githubusercontent.com/34382639/34641693-46d173c6-f308-11e7-9843-c2fc7f35c932.PNG)

windows version

**Comment by romansemko** [comment]
Need to give it more space. Will take care of that!

**Comment by ssssss789** [comment]
use http://localhost:14265, you can mouse mark it, press ctrl+c and ctrl+v you can copy http://localhost:14265

**Comment by witwit** [comment]
Fixed with #12 
![bolero-gui-resized](https://user-images.githubusercontent.com/1893589/34667151-0c0e3e02-f468-11e7-8092-a87d4e1ea3f3.png)
