### ISSUE TITLE
Problems with syncing on Windows

### ISSUE THREAD

**Issue by ghost** [SemkoDev/bolero.fun#50]
Continuation of this closed issue: https://github.com/SemkoDev/bolero.fun/issues/34.

The sync on Windows still doesn't work. I'm running version 0.1.13 and it has been running for more than 48 hours. IRI synchronized still shows: 243000/336639. The size of the .bolero\db is now around 10.6GB.

**Comment by jlariv** [comment]
I also have this issue, Win7 64, java 8 update 161, 16gb ram, latest bolero version. Tried to restart sync by deleting DB folder twice. Didn't find anything relevant in the log.

**Comment by xq0404** [comment]
forward: On windows, the snapshot downloading is disabled at this moment, unfortunately. It has to manually synchronise, which is currently quite painful on all Windows versions. We are trying to find a solution to make IRI/RocksDB work on Windows.

**Comment by romansemko** [comment]
Please download and try 0.1.14. As of now the database is about 20MB and should sync much faster on windows.
