### ISSUE TITLE
Error: IRI exited with status 1

### ISSUE THREAD

**Issue by ghost** [SemkoDev/bolero.fun#55]
Hi
Just download 0.1.14. I did not have any problem since 0.1.12, but now I'm getting "Error: IRI exited with status 1". I've nothing else done, than download new version and unpack into a new folder.

WIN10, attached the logfile.

May you help out?
Thanks 
Florian
[current.log](https://github.com/SemkoDev/bolero.fun/files/1674861/current.log)

**Comment by stereu** [comment]
#45 see this, solution is already posted there. Please check existing issues before creating the same one again.

**Comment by romansemko** [comment]
Duplicate of #45 , please use it for reference. A possible "automated" fix is coming today/tomorrow using the solution posted in #45
