### ISSUE TITLE
Not syncronising?

### ISSUE THREAD

**Issue by AgentDark** [SemkoDev/bolero.fun#58]
![unbenannt](https://user-images.githubusercontent.com/36016754/35652185-dd6c9714-06e2-11e8-8c54-84c4df3967b7.JPG)

Everything seems to be fine, but the .bolero folder is around 60 MB (not increasing). I cannot login in lightwallet because "not synced".

What is the problem?
Thanks in advance!

**Comment by romansemko** [comment]
This is a bug in Bolero that displays the database as synchronised even though it is still at the original point of 338000 (will be fixed today/tomorrow). Just leave it running for an hour or two. Does it change? If not, please post here your "current.log" located in the ".bolero" folder, thanks!

**Comment by xq0404** [comment]
I'm testing Alpha 0.1.15 under Windows 7. I'm waiting patiently for the IRI Synchronized? to change to yes (338000/338000). Hopefully there is a downloading status display.

**Comment by romansemko** [comment]
It usually happens very quickly. First the IRI stays for some time at 338000, then it starts jumping the numbers. Let me know how it goes!

**Comment by xq0404** [comment]
For more than an hour now， it is still 
IRI Synchronized? No (338000/338000)

**Comment by romansemko** [comment]
what does your log say? can you post your ".bolero/current.log" located in your home folder?

**Comment by xq0404** [comment]
Thu Feb 01 2018 15:41:53 GMT+0800 (中国标准时间) system: Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

Thu Feb 01 2018 15:41:53 GMT+0800 (中国标准时间) system: Java version line: [java version "1.8.0_161"
]
Thu Feb 01 2018 15:41:53 GMT+0800 (中国标准时间) system: Java version detected: [1.8.0_161
]
Thu Feb 01 2018 15:41:53 GMT+0800 (中国标准时间) iri: starting...
Thu Feb 01 2018 15:41:54 GMT+0800 (中国标准时间) iri: STDOUT: 02/01 15:41:54.571 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.2.1
Thu Feb 01 2018 16:55:35 GMT+0800 (中国标准时间) iri: STDOUT: 02/01 16:55:35.136 [XNIO-1 task-15] INFO  com.iota.iri.service.API - Adding neighbor: tcp://iota2.3n.no:15600

Thu Feb 01 2018 16:55:39 GMT+0800 (中国标准时间) iri: STDOUT: 02/01 16:55:39.257 [XNIO-1 task-17] INFO  com.iota.iri.service.API - Removing neighbor: tcp://93.140.116.221:15600

Thu Feb 01 2018 16:55:44 GMT+0800 (中国标准时间) iri: STDOUT: 02/01 16:55:44.778 [XNIO-1 task-19] INFO  com.iota.iri.service.API - Removing neighbor: udp://nelson.vanityfive.de:14600

**Comment by romansemko** [comment]
Hmm, can you attach the whole file, this only looks as the first part of it...

**Comment by xq0404** [comment]
[log for fun.txt](https://github.com/SemkoDev/bolero.fun/files/1684818/log.for.fun.txt)

**Comment by romansemko** [comment]
Hmm, it almost looks as if your ports are closed. Could you check that your UDP port 14600 and TCP port 15600 are open?

You can also try using the online tool to check your TCP port while running Bolero: 
https://www.yougetsignal.com/tools/open-ports/
Just input the IP (should be pre-filled by your IP by default) and the port number: 15600. If it's says that it's closed, it means that other neighbours cannot contact your node form the outside.

**Comment by xq0404** [comment]
Yes， they are closed. Thank you.

**Comment by xq0404** [comment]
I have just test the program under Windows 10 at home.  It shows IRI exited with status 1


![win10](https://user-images.githubusercontent.com/20359673/35678648-2eeeb822-078f-11e8-8402-456f1e7511ac.JPG)
[IRI exited with status 1-log.txt](https://github.com/SemkoDev/bolero.fun/files/1685485/IRI.exited.with.status.1-log.txt)

**Comment by AgentDark** [comment]
As the thread starter I would like to inform you, that my problem as well was the closed ports (I accidentally opened them for the wrong device).

Now everything works fine and thank you very much for your response. Keep up the good work.
