### ISSUE TITLE
REMOTE_LIMIT_API on bolero/nelson nodes

### ISSUE THREAD

**Issue by huggre** [SemkoDev/bolero.fun#59]
Hi, im currently doing some testing with the PyOTA library and need my bolero VPS node to perform functions such as AttachToTange. How can i set the REMOTE_LIMIT_API settings in bolero/nelson?

**Comment by romansemko** [comment]
Hi, in Bolero, there is no way to set IRI settings.

For Nelson, just add this configuration to your IRI, as you usually would on a plain vanilla IRI installation.

**Comment by huggre** [comment]
OK, thanks Roman. I will switch to Nelson
