### ISSUE TITLE
Database download stuck on 99.99%

### ISSUE THREAD

**Issue by ghost** [SemkoDev/bolero.fun#7]
If download the database, it stucks at 99.99%. After shut down the windows process and restaring Bolero, everything works fine. Maybe thats an UI issue for not jumping to 100%. Showing "download complete, please restart Bolero" message would be great

**Comment by romansemko** [comment]
It is stuck, while the database gets extracted. It is just not shown like that. Will improve.

Leaving this open for reference.

**Comment by witwit** [comment]
I will take care of showing the info about "extracting".
