### ISSUE TITLE
Bolero fails to find java with "error: java is not installed" on Linux

### ISSUE THREAD

**Issue by joshirio** [SemkoDev/bolero.fun#9]
```
$ java -version
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
```
OS: Arch Linux, same on Manjaro
Java installed: JRE and JDK OpenJDK version 9

Looks like Bolero is unable to find java.
Any idea?

**Comment by footloosejava** [comment]
same here. also openjdk version "9".

**Comment by r-c-k** [comment]
same

**Comment by witwit** [comment]
@romansemko bolero.lib system.js:61, I guess the version test is buggy

**Comment by olaf-2** [comment]
Yes. With OpenJDK it prints
```
$ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (....)
OpenJDK 64-Bit Server VM (....)
```
so `new RegExp('java version').test(data)` returns `false`.

**Comment by CobblerSalad** [comment]
I am on Ubuntu 16 and was able to fix this.
I had to install Oracle Java 8 via PPA with these lines:
`sudo add-apt-repository ppa:webupd8team/java`

`sudo apt-get update`

`sudo apt-get install oracle-java8-installer`

After that Bolero no longer gave the "Java is not installed" error

**Comment by romansemko** [comment]
I will add a check for openjdk
